# Generated by Django 5.2.7 on 2025-10-31 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_property_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='residential_complex',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
